<a href="https://colab.research.google.com/github/JasmineVan/NeuralNetworkML/blob/main/Midterm_Ex3_NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import thư viện

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tensorflow.keras import layers
from tensorflow.keras import models
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt

# Classification

In [ ]:
col_names = ['Sex','Length','Diameter','Height','Whole weight','Shucked weight','Viscera weight','Shell weight','Rings']
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ML/abalone.data", names=col_names)
df.head(5)

Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

## Data preprocessing

In [ ]:
# Label encoder cho cột Sex
col_encode = ['Sex']

LE = LabelEncoder()
df[col_encode] = df[col_encode].apply(LE.fit_transform)
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0    2   0.455     0.365   0.095        0.5140          0.2245   
1    2   0.350     0.265   0.090        0.2255          0.0995   
2    0   0.530     0.420   0.135        0.6770          0.2565   
3    2   0.440     0.365   0.125        0.5160          0.2155   
4    1   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

In [ ]:
df['Rings'] = df['Rings'].apply(lambda x: 0 if x < 9 else (1 if x <= 10 else 2))
df.drop(df[df['Height']==0].index, axis=0)

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0       2   0.455     0.365   0.095        0.5140          0.2245   
1       2   0.350     0.265   0.090        0.2255          0.0995   
2       0   0.530     0.420   0.135        0.6770          0.2565   
3       2   0.440     0.365   0.125        0.5160          0.2155   
4       1   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    0   0.565     0.450   0.165        0.8870          0.3700   
4173    2   0.590     0.440   0.135        0.9660          0.4390   
4174    2   0.600     0.475   0.205        1.1760          0.5255   
4175    0   0.625     0.485   0.150        1.0945          0.5310   
4176    2   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500      2  
1             0.0485        0.0700      0  
2             0.1415        0.2100      1  
3             0.1140        0.1550      1  
4             0.0395        0.0550      0  
...              ...           ...    ...  
4172          0.2390        0.2490      2  
4173          0.2145        0.2605      1  
4174          0.2875        0.3080      1  
4175          0.2610        0.2960      1  
4176          0.3765        0.4950      2  

[4175 rows x 9 columns]

In [ ]:
X = df.iloc[:,0:8]
print(X.shape)
print(X[:5])

(4177, 8)
   Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0    2   0.455     0.365   0.095        0.5140          0.2245   
1    2   0.350     0.265   0.090        0.2255          0.0995   
2    0   0.530     0.420   0.135        0.6770          0.2565   
3    2   0.440     0.365   0.125        0.5160          0.2155   
4    1   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  
0          0.1010         0.150  
1          0.0485         0.070  
2          0.1415         0.210  
3          0.1140         0.155  
4          0.0395         0.055  


In [ ]:
y = df.iloc[:,8]
print(y.shape)
print(y[:5])

(4177,)
0    2
1    0
2    1
3    1
4    0
Name: Rings, dtype: int64


In [ ]:
y = to_categorical(y)
print(y[:2])

[[0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(3341, 8)
(3341, 3)
Test:
(836, 8)
(836, 3)


In [ ]:
model = models.Sequential()
model.add(layers.Dense(16, activation='tanh'))
model.add(layers.Dense(32, activation='sigmoid'))
model.add(layers.Dense(64, activation='sigmoid'))
model.add(layers.Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', 
              metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,epochs=50, batch_size=10, verbose=2)

Epoch 1/50
335/335 - 2s - loss: 1.0332 - accuracy: 0.4648 - 2s/epoch - 5ms/step
Epoch 2/50
335/335 - 1s - loss: 0.8853 - accuracy: 0.5573 - 597ms/epoch - 2ms/step
Epoch 3/50
335/335 - 1s - loss: 0.8686 - accuracy: 0.5669 - 649ms/epoch - 2ms/step
Epoch 4/50
335/335 - 1s - loss: 0.8629 - accuracy: 0.5732 - 706ms/epoch - 2ms/step
Epoch 5/50
335/335 - 1s - loss: 0.8544 - accuracy: 0.5747 - 627ms/epoch - 2ms/step
Epoch 6/50
335/335 - 1s - loss: 0.8506 - accuracy: 0.5735 - 717ms/epoch - 2ms/step
Epoch 7/50
335/335 - 1s - loss: 0.8355 - accuracy: 0.5858 - 761ms/epoch - 2ms/step
Epoch 8/50
335/335 - 1s - loss: 0.8279 - accuracy: 0.5938 - 590ms/epoch - 2ms/step
Epoch 9/50
335/335 - 1s - loss: 0.8148 - accuracy: 0.6031 - 630ms/epoch - 2ms/step
Epoch 10/50
335/335 - 1s - loss: 0.8032 - accuracy: 0.6082 - 867ms/epoch - 3ms/step
Epoch 11/50
335/335 - 1s - loss: 0.7934 - accuracy: 0.6193 - 779ms/epoch - 2ms/step
Epoch 12/50
335/335 - 1s - loss: 0.7908 - accuracy: 0.6187 - 627ms/epoch - 2ms/step
Epoc

In [ ]:
y_pred = model.predict(X_test)
print(y_pred[:2])

[[0.03744915 0.32828552 0.6342653 ]
 [0.15922385 0.31297147 0.5278047 ]]


In [ ]:
y_pred = y_pred.argmax(axis=1)
y_pred = to_categorical(y_pred)
print(y_pred[:2])
print(y_test[:2])
print(y_pred.shape, y_test.shape)

[[0. 0. 1.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]]
(836, 3) (836, 3)


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.86      0.79       304
           1       0.54      0.49      0.51       253
           2       0.73      0.66      0.69       279

   micro avg       0.68      0.68      0.68       836
   macro avg       0.67      0.67      0.67       836
weighted avg       0.68      0.68      0.68       836
 samples avg       0.68      0.68      0.68       836



# Regression

In [ ]:
df_reg = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ML/hour.csv")
df_reg.head(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [ ]:
df_reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     17379 non-null  int64  
 1   dteday      17379 non-null  object 
 2   season      17379 non-null  int64  
 3   yr          17379 non-null  int64  
 4   mnth        17379 non-null  int64  
 5   hr          17379 non-null  int64  
 6   holiday     17379 non-null  int64  
 7   weekday     17379 non-null  int64  
 8   workingday  17379 non-null  int64  
 9   weathersit  17379 non-null  int64  
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64  
 15  registered  17379 non-null  int64  
 16  cnt         17379 non-null  int64  
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB


In [ ]:
df_reg = df_reg.rename(columns={'weathersit':'weather',
                       'yr':'year',
                       'mnth':'month',
                       'hr':'hour',
                       'hum':'humidity',
                       'cnt':'count'})

df_reg = df_reg.drop(columns = ['instant' , 'dteday' , 'year'])

In [ ]:
df_reg.head(5)

season  month  hour  holiday  weekday  workingday  weather  temp   atemp  \
0       1      1     0        0        6           0        1  0.24  0.2879   
1       1      1     1        0        6           0        1  0.22  0.2727   
2       1      1     2        0        6           0        1  0.22  0.2727   
3       1      1     3        0        6           0        1  0.24  0.2879   
4       1      1     4        0        6           0        1  0.24  0.2879   

   humidity  windspeed  casual  registered  count  
0      0.81        0.0       3          13     16  
1      0.80        0.0       8          32     40  
2      0.80        0.0       5          27     32  
3      0.75        0.0       3          10     13  
4      0.75        0.0       0           1      1

In [ ]:
cols = ['weather','temp','atemp','humidity','windspeed','casual','registered']
df_reg[cols]

weather  temp   atemp  humidity  windspeed  casual  registered
0            1  0.24  0.2879      0.81     0.0000       3          13
1            1  0.22  0.2727      0.80     0.0000       8          32
2            1  0.22  0.2727      0.80     0.0000       5          27
3            1  0.24  0.2879      0.75     0.0000       3          10
4            1  0.24  0.2879      0.75     0.0000       0           1
...        ...   ...     ...       ...        ...     ...         ...
17374        2  0.26  0.2576      0.60     0.1642      11         108
17375        2  0.26  0.2576      0.60     0.1642       8          81
17376        1  0.26  0.2576      0.60     0.1642       7          83
17377        1  0.26  0.2727      0.56     0.1343      13          48
17378        1  0.26  0.2727      0.65     0.1343      12          37

[17379 rows x 7 columns]

In [ ]:
X = df_reg[cols]
y = df_reg['count']
print(X[:2])
print(y[:2])

   weather  temp   atemp  humidity  windspeed  casual  registered
0        1  0.24  0.2879      0.81        0.0       3          13
1        1  0.22  0.2727      0.80        0.0       8          32
0    16
1    40
Name: count, dtype: int64


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(13903, 7)
(13903,)
Test:
(3476, 7)
(3476,)


In [ ]:
normalizer = layers.Normalization(axis=-1)

In [ ]:
normalizer.adapt(np.array(X_train))

In [ ]:
print(normalizer.mean.numpy())

[[  1.4231471    0.4979401    0.4767292    0.6267849    0.18966085
   35.679085   153.68541   ]]


In [ ]:
first = np.array(X[:1])

with np.printoptions(precision=2, suppress=True):
  print('First example:', first)
  print()
  print('Normalized:', normalizer(first).numpy())

First example: [[ 1.    0.24  0.29  0.81  0.    3.   13.  ]]

Normalized: [[-0.66 -1.34 -1.1   0.95 -1.55 -0.66 -0.93]]


In [ ]:
model = models.Sequential([
      normalizer,
      layers.Dense(64, activation='relu'),
      layers.Dense(64, activation='relu'),
      layers.Dense(1)     
])

model.compile(loss='mean_absolute_error', optimizer='adam', 
              metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization (Normalizatio  (None, 7)                15        
 n)                                                              
                                                                 
 dense_4 (Dense)             (None, 64)                512       
                                                                 
 dense_5 (Dense)             (None, 64)                4160      
                                                                 
 dense_6 (Dense)             (None, 1)                 65        
                                                                 
Total params: 4,752
Trainable params: 4,737
Non-trainable params: 15
_________________________________________________________________


In [ ]:
history = model.fit(X_train,y_train,epochs=100, verbose=2)

Epoch 1/100
435/435 - 1s - loss: 96.8498 - accuracy: 0.0093 - 870ms/epoch - 2ms/step
Epoch 2/100
435/435 - 1s - loss: 7.2118 - accuracy: 0.0081 - 518ms/epoch - 1ms/step
Epoch 3/100
435/435 - 0s - loss: 1.7341 - accuracy: 0.0079 - 480ms/epoch - 1ms/step
Epoch 4/100
435/435 - 0s - loss: 0.8997 - accuracy: 0.0082 - 483ms/epoch - 1ms/step
Epoch 5/100
435/435 - 0s - loss: 0.6558 - accuracy: 0.0078 - 463ms/epoch - 1ms/step
Epoch 6/100
435/435 - 0s - loss: 0.5265 - accuracy: 0.0083 - 468ms/epoch - 1ms/step
Epoch 7/100
435/435 - 0s - loss: 0.4806 - accuracy: 0.0082 - 471ms/epoch - 1ms/step
Epoch 8/100
435/435 - 0s - loss: 0.4281 - accuracy: 0.0086 - 466ms/epoch - 1ms/step
Epoch 9/100
435/435 - 0s - loss: 0.3809 - accuracy: 0.0085 - 460ms/epoch - 1ms/step
Epoch 10/100
435/435 - 0s - loss: 0.3743 - accuracy: 0.0085 - 487ms/epoch - 1ms/step
Epoch 11/100
435/435 - 0s - loss: 0.3499 - accuracy: 0.0086 - 467ms/epoch - 1ms/step
Epoch 12/100
435/435 - 0s - loss: 0.3598 - accuracy: 0.0081 - 483ms/epoch

In [ ]:
test_results = {}

test_results['dnn_model'] = model.evaluate(X_test, y_test, verbose=2)

109/109 - 0s - loss: 0.3739 - accuracy: 0.0081 - 215ms/epoch - 2ms/step
